-- MySQL Script generated by MySQL Workbench
-- 12/18/16 22:13:58
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema Estudent
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Estudent
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Estudent` DEFAULT CHARACTER SET utf8 ;
USE `Estudent` ;

-- -----------------------------------------------------
-- Table `Estudent`.`Drzava`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estudent`.`Drzava` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estudent`.`Naslov`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estudent`.`Naslov` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ulica` VARCHAR(45) NOT NULL,
  `postnaStevilka` INT NULL,
  `Drzava_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Naslov_Drzava_idx` (`Drzava_id` ASC),
  CONSTRAINT `fk_Naslov_Drzava`
    FOREIGN KEY (`Drzava_id`)
    REFERENCES `Estudent`.`Drzava` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estudent`.`Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estudent`.`Student` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `eposta` VARCHAR(45) NOT NULL,
  `geslo` VARBINARY(64) NOT NULL,
  `uporabniskoIme` VARCHAR(45) NOT NULL,
  `mobilniTelefon` INT NULL,
  `stacionarniTelefon` INT NULL,
  `Naslov_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Uporabnik_Naslov1_idx` (`Naslov_id` ASC),
  CONSTRAINT `fk_Uporabnik_Naslov1`
    FOREIGN KEY (`Naslov_id`)
    REFERENCES `Estudent`.`Naslov` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estudent`.`Predmet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estudent`.`Predmet` (
  `sifraPredmeta` INT NOT NULL,
  `nazivPredmeta` VARCHAR(45) NOT NULL,
  `kreditniTocki` INT NULL,
  PRIMARY KEY (`sifraPredmeta`),
  UNIQUE INDEX `Naziv predmeta_UNIQUE` (`nazivPredmeta` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estudent`.`Profesor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estudent`.`Profesor` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ime` VARCHAR(45) NOT NULL,
  `priimek` VARCHAR(45) NOT NULL,
  `eposta` VARCHAR(45) NOT NULL,
  `geslo` VARBINARY(64) NOT NULL,
  `uporabniskoIme` VARCHAR(45) NOT NULL,
  `mobilniTelefon` INT NULL,
  `stacionarniTelefon` INT NULL,
  `Naslov_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_Uporabnik_Naslov1_idx` (`Naslov_id` ASC),
  CONSTRAINT `fk_Uporabnik_Naslov1`
    FOREIGN KEY (`Naslov_id`)
    REFERENCES `Estudent`.`Naslov` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estudent`.`Izpit`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estudent`.`Izpit` (
  `datum` DATETIME NOT NULL,
  `ocena` INT NOT NULL,
  `Uporabnik_id` INT NOT NULL,
  `Predmet_Sifra predmeta` INT NOT NULL,
  `Profesor_id` INT NOT NULL,
  PRIMARY KEY (`datum`),
  INDEX `fk_Izpit_Uporabnik1_idx` (`Uporabnik_id` ASC),
  INDEX `fk_Izpit_Predmet1_idx` (`Predmet_Sifra predmeta` ASC),
  INDEX `fk_Izpit_Profesor1_idx` (`Profesor_id` ASC),
  CONSTRAINT `fk_Izpit_Uporabnik1`
    FOREIGN KEY (`Uporabnik_id`)
    REFERENCES `Estudent`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izpit_Predmet1`
    FOREIGN KEY (`Predmet_Sifra predmeta`)
    REFERENCES `Estudent`.`Predmet` (`sifraPredmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Izpit_Profesor1`
    FOREIGN KEY (`Profesor_id`)
    REFERENCES `Estudent`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Estudent`.`Student_has_Predmet`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Estudent`.`Student_has_Predmet` (
  `Student_id` INT NOT NULL,
  `Predmet_sifraPredmeta` INT NOT NULL,
  `Profesor_id` INT NOT NULL,
  PRIMARY KEY (`Student_id`, `Predmet_sifraPredmeta`),
  INDEX `fk_Student_has_Predmet_Predmet1_idx` (`Predmet_sifraPredmeta` ASC),
  INDEX `fk_Student_has_Predmet_Student1_idx` (`Student_id` ASC),
  INDEX `fk_Student_has_Predmet_Profesor1_idx` (`Profesor_id` ASC),
  CONSTRAINT `fk_Student_has_Predmet_Student1`
    FOREIGN KEY (`Student_id`)
    REFERENCES `Estudent`.`Student` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Predmet_Predmet1`
    FOREIGN KEY (`Predmet_sifraPredmeta`)
    REFERENCES `Estudent`.`Predmet` (`sifraPredmeta`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Student_has_Predmet_Profesor1`
    FOREIGN KEY (`Profesor_id`)
    REFERENCES `Estudent`.`Profesor` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
